### ISSUE TITLE
Precourse Preparation

### ISSUE THREAD

**Issue by gilbertwat** [node4jserhk/Javascript_Ignite_2015#1]
- [x] EDM to participants
  - [x] BYOD
  - [x] Github Account Set up
- [ ] Check Equipments List
  - [ ] Camcorder
  - [ ] Projector
  - [ ] HDMI to VGA adapters
  - [ ] Thunderbolt to VGA adapter
  - [ ] iPad / iPhone for Periscope / Meerkat
- [ ] Dry Run Session 1 x 2
  - [ ] Introduction
  - [ ] Javascript 101
  - [ ] Little Competition
  - [ ] Code Academy Part 1-5

**Comment by capsulejj** [comment]
Tutors are nice and teach really well.

**Comment by gilbertwat** [comment]
Thanks @capsulejj !!! A very kind word and keeping us bumped!
